name: BookStack Knowledge Sync

on:
  issues:
    types: [opened, edited, closed]

jobs:
  sync-knowledge:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: checkout repo
        uses: actions/checkout@v2

      - name: debug ls files
        run: ls -al

      - name: installing dependencies
        run: npm i marked node-fetch

      - name: Sync Issue to BookStack
        env:
          BOOKSTACK_API_ID: ${{ secrets.BOOKSTACK_API_ID }}
          BOOKSTACK_API_SECRET: ${{ secrets.BOOKSTACK_API_SECRET }}
          BOOKSTACK_URL: ${{ secrets.BOOKSTACK_URL }}
          BOOKSTACK_BOOK_ID: ${{ secrets.BOOKSTACK_BOOK_ID }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_STATE: ${{ github.event.issue.state }}
          GITHUB_EVENT_ACTION: ${{ github.event.action }}
        run: node issues-to-bookstack.mjs
